"""empty message

Revision ID: 0255cee10faa
Revises: b8d2b868f6f9
Create Date: 2020-03-10 23:23:30.405030

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy import create_engine  

# revision identifiers, used by Alembic.
revision = '0255cee10faa'
down_revision = 'b8d2b868f6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    db_string = "postgres://archanapur@localhost:5432/fyyur"
    db = create_engine(db_string)  
    db.execute('ALTER TABLE fyyur_app."Artist" ADD COLUMN seeking_venue BOOLEAN')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    db_string = "postgres://archanapur@localhost:5432/fyyur"
    db = create_engine(db_string)  
    db.execute('ALTER TABLE fyyur_app."Artist" drop COLUMN seeking_venue')
    # ### end Alembic commands ###
